### ISSUE TITLE
Password.DeriveKey fails when using Argon2 and the latest version of libsodium

### ISSUE THREAD

**Issue by charonn0** [charonn0/RB-libsodium#4]
I have almost no information about why this occurs, but using `crypto_pwhash` or `crypto_pwhash_argon2i` don't seem to work anymore.

Workaround: use scrypt, which doesn't seem to have a problem.

**Comment by charonn0** [comment]
Thanks to some help from the libsodium's main developer, I've been able to identify the problem:

* `size_t` is not 64 bits on 32 bit platforms, but the `MemLimit` parameter to `crypto_pwhash` was declared as a `UInt64`. Changed to a `UInt32`.
* `crypto_pwhash_ALG_DEFAULT` is not zero (possibly also needs its Integer type changed)

Need to review all calls into libsodium to verify we're using the right-sized integers.

To do: make it 64-bit ready

**Comment by jedisct1** [comment]
RealBasic has a `UInteger` type. This is probably what you want to use for all C `size_t` values. And `Integer` for all `int` values. 

`Double` and `Uint32` should not be needed at all.

**Comment by charonn0** [comment]
`UInteger` was added in 2014. For backwards compatibility with older versions (i.e. what I'm using) a literal `UInt32` or `UInt64` must be used for unsigned integers. 

64-bit readiness is not a top priority just yet, for backward compatibility reasons and also because the 64-bit compiler is still experimental. So I think using `UInt32` when a `size_t` is expected is OK, at least for now.

**Comment by jedisct1** [comment]
Sad.

**Comment by charonn0** [comment]
I'm sorry?

**Comment by charonn0** [comment]
I guess I must have offended you somehow. If so, I'm sorry. If not, please clarify your sadness.
